spring:
  application:
    name: BookConnect
  servlet:
    multipart:
      max-request-size: 50MB
  datasource:
    url: jdbc:mariadb://localhost:3306/book_connect?useSSL=false
    username: root
    password: Sumit@7033
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
springdoc:
  default-consumes-media-type: application/json
